[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=60",
    "setuptools-scm>=8.0"
    ]

[project]
name = "fms-model-optimization"
version="0.0.1"
description = "FMS Model Optimization"
authors = [
  {name = "Andrea Fasoli"},
  {name = "Brandon Groth"},
  {name = "Charlie Liu"},
  {name = "Derrick Liu"},
  {name = "Naigang Wang"},
  {name = "Thara Palanivel"},
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = "~=3.9"
keywords = ['quantization', 'python', 'pytorch']
classifiers=[
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
"torch>=2.2.1",
"numpy",
"tqdm==4.66.6",
"tensorboard==2.8.0",
"notebook",
"matplotlib==3.4.3",
"torchvision>=0.8",
"graphviz",
"cGraph==0.1",
"transformers",
"packaging==24.0"
]

[tool.setuptools.packages.find]
exclude = ["tests", "tests.*"]
namespaces = false

[project.urls]
Homepage = "https://github.com/foundation-model-stack/fms-model-optimization"
Repository = "https://github.com/foundation-model-stack/fms-model-optimization"
Issues = "https://github.com/foundation-model-stack/fms-model-optimization/issues"
